packages:
  - "."

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  maplibre-gl: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js
  - esbuild
  - maplibre-gl
  - protobufjs
  - unrs-resolver
  - vue-demi
